[project]
name = "streamlit_editorialcat"
version = "0.1.0"
description = "Add a short description here"
authors = ["Junsok Huhh <anarinsk@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
streamlit = "1.26.0.*"
pandas = "2.1.0.*"
plotly = "5.16.1.*"
gspread = "5.7.1.*"
